- src/lpmd_hfi.c
The while loop in function send_and_recv_msgs is checking for err > 0 however err is not being re-assigned from the return to the call to nl_recvmsgs and hence the loop will spin for ever. Fix this by assigning err.
> lpmd_hfi.c: fix infinite loop due to missing err assignment

- configure.ac
Release 0.0.2 after a series of cleanups/fixes.
> intel_lpmd: intel_lpmd 0.0.2 release

- src/lpmd_proc.c
Check for pthread_create() return value.
Addresses https://github.com/intel/intel-lpmd/issues/15
> intel_lpmd: Check for pthread_create() return value

- src/lpmd_cpu.c
This PR address following issues
1. Do strict CPU model check to prevent unexpected behavior on random platforms. Now intel_lpmd runs on ADL/RPL/MTL platforms only.
2. Detect Lcore by checking CPUID.4 directly instead of checking /sys/devices/system/cpu/cpuX/cache/. This removes dependency of a known kernel gap.
3. Do strict check for Ecore Modules. Only a Linux cluster that has 4 cores and has Atom CPUs is a Ecore module.
4. Fix CPUID.7 reading. Force using subleaf 0 to make sure we don't read random value.
> CPUID related fixes and enhancements

- Makefile.am
- configure.ac
- lpmd-resource.gresource.xml
- src/lpmd.h
- src/lpmd_cpu.c
- src/lpmd_dbus_server.c
- src/lpmd_hfi.c
- src/lpmd_main.c
- src/lpmd_proc.c
- tests/lpm_test_interface.sh
Release 0.0.3, including
1. Conversion from glib-dbus to GDBus.
2. Add handling for CPU hotplug.
3. Use strict CPU model check to allow intel_lpmd running on
1.1 validated platforms only. Including ADL/RPL/MTL for now.
1.2 CPUID.7 Hybrid bit is set
1.3 /sys/firmware/acpi/pm_profile returns 2 (mobile platform)
4. Use cpuid() to detect Lcores instead of using cache sysfs.
5. Enhance Ecore module detection
6. Fix pthread error handling, suggested by ColinIanKing.
7. Werror Fixes from aekoroglu.
> intel_lpmd 0.03 release

- src/lpmd_cpu.c
If the fscanf fails we end up with online in a undefined uninitalized state. Fix this by initializing online to zero.
Cleans up clang scan build warning:
src/lpmd_cpu.c:692:7: warning: Branch condition evaluates to a garbage value [core.uninitialized.Branch]
692 |                 if (!online)
|                     ^~~~~~~
> lpmd_cpu: ensure online is initialized to zero

- Makefile.am
- configure.ac
- data/Makefile.am
- data/org.freedesktop.intel_lpmd.service.in
- tests/lpm_test_interface.sh
- tools/Makefile
Reverts intel/intel-lpmd#23
because some of the patches miss "Signed-off-by" tag.
> Revert "automake and autoconf improvements"

- src/lpmd_cpu.c
Reverts intel/intel-lpmd#22
because the patch misses "Signed-off-by" tag.
> Revert "Update lpmd_cpu.c"

- configure.ac
- data/intel_lpmd_config.xml
- data/intel_lpmd_config_examples.xml
- man/intel_lpmd_config.xml.5
- src/lpmd.h
- src/lpmd_config.c
- src/lpmd_cpu.c
- src/lpmd_hfi.c
- src/lpmd_irq.c
- src/lpmd_proc.c
- src/lpmd_util.c
intel_lpmd 0.0.4 release, including
1. Enhance HFI monitor so that it can handle back-to-back HFI LPM hints.
Previously it only handles first HFI LPM hints and ignore the sub-sequential HFI LPM hints until it exits Low Power mode.
2. Enhance HFI monitor to handle HFI hints for banned CPUs.
3. Introduce support for multiple Low Power states.
With this, intel_lpmd can define multiple Low Power states that have different
requirements for EPP/EPB/ITMT setting, IRQ migration, and task migration.
And enter different Low Power state based on different utilization threshold.
4. Introduce support for work load type hint.
Intel firmware is able to predict workload type and expose this hint to userspace.
Add support to define Low Power states and switch between them based on workload type hint.
5. …
> intel_lpmd 0.0.4 release 

- src/lpmd_cpu.c
- src/lpmd_irq.c
- src/lpmd_util.c
Fix below compile warnings
src/lpmd_cpu.c: In function ‘set_epp’:
src/lpmd_cpu.c:567:13: warning: unused variable ‘epp’ [-Wunused-variable]
567 |         int epp;
|             ^~~
src/lpmd_cpu.c: In function ‘get_tdp’:
src/lpmd_cpu.c:1777:53: warning: ‘%s’ directive output may be truncated writing up to 255 bytes into a region of size 236 [-Wformat-truncation=]
1777 |                 snprintf (path, MAX_STR_LENGTH, "%s/%s/name", PATH_RAPL, entry->d_name);
|                                                     ^~
src/lpmd_cpu.c:1777:17: note: ‘snprintf’ output between 26 and 281 bytes into a destination of size 256
1777 |                 snprintf (path, MAX_STR_LENGTH, "%s/%s/name", PATH_RAPL, entry->d_name);
|                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ …
> Fix compile warnings

- configure.ac
This release only includes a series of fixes/cleanups for v0.0.4.
1. Fix compiling warnings with -Wall.
2. Remove unintended default config file change to keep it unchanged
since v0.0.3.
> intel_lpmd: intel_lpmd 0.0.5 release

- Makefile.am
- configure.ac
- src/lpmd.h
- src/lpmd_dbus_server.c
- tools/Makefile
- tools/intel_lpmd_control.c
Since the dbus-glib was already deprecated, the related portion of codes for lpmd can be removed. This work entirely deprecated dbus-glib and made the dbus implementation based on GDbus.
> Deprecate the dbus-glib dependency

- configure.ac
This release
- removes the automake and autoconf improvements because a regression is found.
- deprecates the dbus-glib dependency.
> intel_lpmd: intel_lpmd 0.0.6 release

- src/lpmd_cpu.c
if the compiler parameter `-Werror=array-bounds` was applied, the compiler complained about the "above array bound" error. This work added a test to ensure the index was not greater than the max array index.
```
src/lpmd_cpu.c: In function ‘add_cpu’:
src/lpmd_cpu.c:408:66: error: array subscript 8 is above array bounds of ‘struct lpm_cpus[7]’ [-Werror=array-bounds=]
408 |                 lpmd_log_debug ("\tDetected %s CPU%d\n", cpumasks[idx].name, cpu);
|                                                          ~~~~~~~~^~~~~
src/lpmd_cpu.c:67:24: note: while referencing ‘cpumasks’
67 | static struct lpm_cpus cpumasks[CPUMASK_MAX] = {
|                        ^~~~~~~~
cc1: all warnings being treated as errors
make[2]: *** [Makefile:686: src/intel_lpmd-lpmd_cpu.o] Error 1
make[1]: *** …
```
> lpmd_cpu: Fix compiler above array bound error

- src/lpmd_cpu.c
snprintf() may return a negative value when an output error is encountered. A negative index can lead to reading or writing outside the bounds of an array. Moreover, snprintf() puts a '\0' at the end of the string so we don't have to put a '\0' manually.
* The functions snprintf() and vsnprintf() write at most size bytes   (including the terminating null byte ('\0')) to str.
> Fix ret may hold a negative value

- man/intel_lpmd.8
- src/lpmd.h
- src/lpmd_cpu.c
- src/lpmd_main.c
current code uses a strict platform check to launch the service on certain platforms that the ILEO has been verified to work.
This includes,
1. the platform must be a hybrid platform (via CPUID)
2. the platform must be a mobile platform (via ACPI)
3. the platform must be in an allowed list (via CPU model)
But this also blocks users who want to experience it on the platforms that don't meet all these criteria.
Introduce parameter "--ignore-platform-check" to ignore such checks.
> Allow probe without platform check

- src/lpmd_util.c
When parsing some columns in /proc/stat fails, ignore the failure. This may cause bogus utilization because it is not a critical falure and things will be back to work when /proc/stat is parsed successfully.
Add a debug message for this case.
This address issue https://github.com/intel/intel-lpmd/issues/52
> Tolerant /proc/stat parsing failure

- configure.ac
This release
- Change lpmd description from "Low Power Mode Daemon" to "Energy Optimizer (lpmd)" because it covers more scenarios.
- Fix invalid cgroup setting during probe, in case lpmd doesn't quit smoothly and cleanups are not done properly, in the previous run.
- Introduce a new parameter "--ignore-platform-check". With it, the platform check is skipped so lpmd can be launched on unvalidated platforms.
- Provide more detailed information when lpmd failed to probe on an unvalidated platform.
- Various of fixes for array bound check, potential memory leak, etc.
- Autotool improvements.
> intel_lpmd: intel_lpmd 0.0.7 release

- src/lpmd_cpu.c
- src/lpmd_dbus_server.c
- src/lpmd_proc.c
gcc static analyzer warns that introspection_data is not being null checked, which could lead to a potential null pointer dereference. Even though error is being checked, it seems prudent to add a null check on introspection_data to make the code more resiliant and also to silence static analysis warnings.
> lpmd_dbus_server: add extra sanity check on introspection_data

- src/lpmd_util.c
In the function parse_proc_stat() check for the return status of calloc(), before using proc_stat_prev and proc_stat_cur.
> Check for calloc failure

- src/lpmd_util.c
Fix a couple of resource leaks on error return paths by closing the opened file.
Fixes: 024706f244ad ("Check for calloc failure")
> Fix file descriptor resource leaks on error return paths

- man/intel_lpmd_config.xml.5
The phrase "Allows to" should be "Allows one to", fix it.
> Manual: Fix grammar mistake found with debian lintian tool

- src/lpmd_util.c
- src/wlt_proxy/state_manager.c
- src/wlt_proxy/state_util.c
Drop unused variables and functions. They caused compile errors when updating the RHEL packages.
> Drop unused variables and functions

- src/lpmd_cgroup.c
- src/lpmd_cpu.c
- src/lpmd_dbus_server.c
- src/lpmd_hfi.c
- src/lpmd_irq.c
- src/lpmd_misc.c
- src/lpmd_state_machine.c
- src/lpmd_util.c
Hi,
The PR fixed the compile errors when applying `-Wall`.
One uninitialized variable was found as described in https://github.com/intel/intel-lpmd/issues/102 needs to be resolved.
Moreover, the commit shown as follows needs your review and verification.
[lpmd_state_machine: Fix incorrect assignment](https://github.com/smallorange/intel-lpmd/commit/a9a0840bba2d4588b1558a56f3c7052d182d01aa)
```
lpmd_state_machine: Fix incorrect assignment
lpmd_state == LPMD_FREEZE; should be lpmd_state = LPMD_FREEZE;
and
lpmd_state == saved_lpmd_state; should be lpmd_state = saved_lpmd_state;
```
Thank you :)
> Fix the errors, including unused variable, function, unused tag, and invalid assignment
